[package]
name = "return_complex_type"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wasm"]
wasm = []
std = []
simulator = ["wasmlanche/simulator", "wasmlanche/std", "std"]
test = ["simulator"]
bindings = ["wasmlanche/bindings"]
futures_executor = []

[dependencies]
wasmlanche = { workspace = true, default-features = false, features = ["wasm"] }
borsh = { version = "0.10.3", default-features = false }
sdk-macros = { path = "../../../sdk-macros" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = "0.4"

[dev-dependencies]
wasmlanche = { workspace = true, features = ["debug", "test", "std", "simulator"] }

[build-dependencies]
wasmlanche-build = { path = "../../../wasmlanche-build" }

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1
