[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[lib]
name = "simulator"
crate-type = ["rlib"]

[dependencies]
libc = "0.2.155"
thiserror = { workspace = true }

[build-dependencies]
bindgen = "0.69.4"
serde_json = "1.0.122"

[features]
default = ["std"]
std = []
