[package]
name = "test-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]
exclude = ["**/target"]

[dependencies]
cosmwasm-std = "1.5.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
