[package]
name = "balance"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmlanche = { workspace = true }
borsh = { workspace = true, features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["rt", "macros"] }
wasmlanche-test = { path = "../../../wasmlanche/wasmlanche-test" }

[build-dependencies]
wasmlanche = { workspace = true, features = ["build"] }
