[package]
name = "async_producer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk-macros = { path = "../../../sdk-macros" }
wasmlanche = { path = "../../../wasmlanche", default-features = false, features = ["wasm"] }
borsh = { version = "0.10.3", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = "0.4"

[features]
default = ["wasm"]
wasm = []

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1
